quarkus.ssl.native: false

quarkus.datasource:
  db-kind: postgresql
  jdbc.url: jdbc:postgresql://${POSTGRESQL_HOST}/${POSTGRESQL_DB}
  driver: org.postgresql.Driver
  username: ${POSTGRESQL_USERNAME}
  password: ${POSTGRESQL_PASSWORD}

quarkus.hibernate-orm:
  dialect: org.hibernate.dialect.PostgreSQL10Dialect
  database.generation: update

"%dev":
  quarkus.hibernate-orm:
    database.generation: drop-and-create
    sql-load-script: test-dataset.sql