quarkus.ssl.native: false

quarkus.datasource.db-kind: h2
quarkus.datasource.jdbc.url: jdbc:h2:mem:test

quarkus.hibernate-orm:
  dialect: org.hibernate.dialect.H2Dialect
  database.generation: update

"%dev":
  quarkus.hibernate-orm:
    database.generation: drop-and-create
    sql-load-script: test-dataset.sql